/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.31
 * Generated at: 2024-10-17 17:21:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<title>Ancient Space and Modern Technology in Ancient India</title>\r\n");
      out.write("<style>\r\n");
      out.write("    body {\r\n");
      out.write("        font-family: Arial, sans-serif;\r\n");
      out.write("        background-color: #f4f4f4;\r\n");
      out.write("        margin: 0;\r\n");
      out.write("        padding: 20px;\r\n");
      out.write("    }\r\n");
      out.write("    header {\r\n");
      out.write("        text-align: center;\r\n");
      out.write("        padding: 50px;\r\n");
      out.write("        background-color: #4CAF50;\r\n");
      out.write("        color: white;\r\n");
      out.write("    }\r\n");
      out.write("    h1 {\r\n");
      out.write("        font-size: 2.5em;\r\n");
      out.write("    }\r\n");
      out.write("    section {\r\n");
      out.write("        margin: 20px 0;\r\n");
      out.write("        padding: 20px;\r\n");
      out.write("        background-color: white;\r\n");
      out.write("        border-radius: 8px;\r\n");
      out.write("        box-shadow: 0 2px 5px rgba(0,0,0,0.1);\r\n");
      out.write("    }\r\n");
      out.write("    h2 {\r\n");
      out.write("        color: #333;\r\n");
      out.write("    }\r\n");
      out.write("    .image-placeholder {\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        height: 200px;\r\n");
      out.write("        background-color: #ccc;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("        line-height: 200px;\r\n");
      out.write("        font-size: 1.5em;\r\n");
      out.write("        color: #666;\r\n");
      out.write("        margin-bottom: 15px;\r\n");
      out.write("    }\r\n");
      out.write("    img {\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        height: auto;\r\n");
      out.write("        border-radius: 8px;\r\n");
      out.write("    }\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<header>\r\n");
      out.write("<h1>Ancient Space and Modern Technology in Ancient India</h1>\r\n");
      out.write("</header>\r\n");
      out.write("\r\n");
      out.write("<section>\r\n");
      out.write("<h2>1. Sage Agastya</h2>\r\n");
      out.write("<img src=\"https://mydattatreya.com/wp-content/uploads/2021/12/6-1.jpg\" alt=\"Image of Sage Agastya\">\r\n");
      out.write("<p>Sage Agastya is one of the most revered sages in Hindu tradition. He is known for his immense knowledge in various fields including astronomy, medicine, and philosophy. Agastya is credited with authoring several texts, including the Agastya Samhita, which contains information on various sciences and technologies.</p>\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("<section>\r\n");
      out.write("<h2>2. Sage Vasishtha</h2>\r\n");
      out.write("<img src=\"https://www.learnkriyayoga.com/wp-content/uploads/2017/02/Yoga-Vasistha-300x248.jpg\" alt=\"Image of Sage Vasishtha\">\r\n");
      out.write("<p>Sage Vasishtha is renowned for his contributions to Vedic literature and is considered one of the seven great sages (Saptarishi). He is known for his wisdom and is often associated with advanced knowledge of architecture and engineering, which is reflected in the construction of the mythical city of Ayodhya.</p>\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("<section>\r\n");
      out.write("<h2>3. Sage Patanjali</h2>\r\n");
      out.write("<img src=\"https://historified.in/wp-content/uploads/2022/05/b72af41e006b62a2ab9eb071d3cc8791-564x560.jpg.webp\" alt=\"Image of Sage Patanjali\">\r\n");
      out.write("<p>Sage Patanjali is best known for his work in yoga and linguistics. His text, the Yoga Sutras, lays the foundation for modern yoga practices and philosophy. He is also credited with the creation of the grammar rules that are still in use today, showcasing the technological advancement in linguistics in ancient India.</p>\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("<section>\r\n");
      out.write("<h2>4. Sage Kapila</h2>\r\n");
      out.write("<img src=\"https://divyakataksham.wordpress.com/wp-content/uploads/2015/10/sage-kapila.jpg\" alt=\"Image of Sage Kapila\">\r\n");
      out.write("<p>Sage Kapila is recognized for his contributions to the philosophy of Sankhya and is often regarded as the father of this school of thought. His teachings emphasize the importance of understanding the universe and consciousness, which reflects a deep understanding of metaphysics and science.</p>\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("<section>\r\n");
      out.write("<h2>5. Sage Charaka</h2>\r\n");
      out.write("<img src=\"https://www.indica.today/wp-content/uploads/2020/02/history-of-ayurveda-640x394.jpg\" alt=\"Image of Sage Charaka\">\r\n");
      out.write("<p>Sage Charaka is considered the father of Ayurveda, the ancient Indian system of medicine. His work, the Charaka Samhita, is a comprehensive text that discusses various aspects of medicine, health, and wellness, showcasing the advanced medical knowledge of ancient India.</p>\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
